### ISSUE TITLE
Compiled Version: Heading nesting issues

### ISSUE THREAD

**Issue by jshank** [OldManUmby/DND.SRD.Wiki#40]
Awesome work, thank you! A small nit on formatting.

In the [compiled md file](https://github.com/OldManUmby/DND.SRD.Wiki/blob/master/Downloads/md/D%26D%205E%20SRD%20Full%20Compile-v0.4.4.md), the headers don't nest properly for at least Races and CLASSES. Races should be at H1/# while Dwarf, Elf, etc should be at H2/##

**Comment by OldManUmby** [comment]
Agreed. I'll have a look. THX!

**Comment by OldManUmby** [comment]
Sorry for the delay; I will be re-compiling with an updated version soon. THX!
