### ISSUE TITLE
Missing content "Beyond 1st Level"

### ISSUE THREAD

**Issue by scarfur** [OldManUmby/DND.SRD.Wiki#42]
**Hey there @OldManUmby** 

_**thanks for your work - this is a great piece of repo :D**_
Yesterday during my play, I recognized that I can't find the 

> how much XP I need for a level up?

 ... table.

Am I dumb or blind or maybe is there a special reason you did not implemented the `Beyond 1st Level` chapter of the SRD? I am wondering because at first it seemed everything is there as described in your [readme.md](https://github.com/OldManUmby/DND.SRD.Wiki/blob/master/README.md) - I must confess **I did not immediately open the srd** to look for other things that might be missing?! And if so, do you need help?

Greetings and keep up the great work!

**Comment by OldManUmby** [comment]
Oh, shit ... good spot. Apparently, it didn't get uploaded to Github. I'll fix it right away and get back to you. THX!

**Comment by OldManUmby** [comment]
Sorry for the delay; I will be re-compiling with an updated version soon. THX!
